# Generated by Django 6.0.3 on 2026-04-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('study_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
